import type { NextPage } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'
import { Container } from 'react-bootstrap'
import employeeList from '../data/employee.json'
import Header from '../components/Header'
import Employees from '../components/Employees'

const Home: NextPage = () => {
  const [teamMemberCount, setCounter] = useState(0)
  const [selectedTeam, setTeam] = useState('B' || localStorage.getItem('selectedTeam'))
  const [employees, setEmployees] = useState( employeeList || localStorage.getItem('employeeList'))
//must give it a default value, otherwise when localStorage is not ready yet, the SSR will conflict with CSR
useEffect(() => {
  localStorage.setItem('employeeList', JSON.stringify(employeeList))
},[employees])

  useEffect(() => {
    localStorage.setItem('selectedTeam', selectedTeam)
  },[selectedTeam])



  const handleTeamSelectionChange = (event: any) => {
    setTeam(event.target.value);
  }
//if clicked employee's team unequal to selectedTeam, transform
  const handleEmployeeCardClick = (event: any) => {
    //sth here
  }
  return (
    <Container>
      <Head>
        <title>team member allocation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header 
        selectedTeam={selectedTeam} 
        teamMemberCount={teamMemberCount} 
      />
      <Employees 
        employees={employees}
        selectedTeam={selectedTeam}
        handleEmployeeCardClick={handleEmployeeCardClick}
        handleTeamSelectionChange={handleTeamSelectionChange}
      />
    </Container>
  )
}

export default Home
