import type { NextPage } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'
import { Container } from 'react-bootstrap'

import Header from '../components/Header'
import TeamMembers from '../components/TeamMembers'
import TeamSelect from '../components/TeamSelect'

const Home: NextPage = () => {
  const [teamMemberCount, setCounter] = useState(0)
  const [selectedTeam, setTeam] = useState(typeof window === 'undefined'? null : localStorage.getItem('selectedTeam'))

  useEffect(() => {
    countTeamMember();
  },[selectedTeam])

  const countTeamMember = () => {
    let teamA = localStorage.getItem('teamA') !== null? localStorage.getItem('teamA') : ''
    let teamB = localStorage.getItem('teamB') !== null? localStorage.getItem('teamB') : ''
    let teamC = localStorage.getItem('teamC') !== null? localStorage.getItem('teamC') : ''
    let teamD = localStorage.getItem('teamD') !== null? localStorage.getItem('teamD') : ''
    switch(selectedTeam) {
      case 'A': 
      teamA !== null? setCounter(JSON.parse(teamA).length) : 0
      case 'B': 
      teamB !== null? setCounter(JSON.parse(teamB).length) : 0
      case 'C': 
      teamC !== null? setCounter(JSON.parse(teamC).length) : 0
      case 'D': 
      teamD !== null? setCounter(JSON.parse(teamD).length) : 0
    }
  }
  return (
    <Container>
      <Head>
        <title>team member allocation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header selectedTeam={selectedTeam} teamMemberCount={teamMemberCount} />
      <TeamSelect />
      <TeamMembers />
    </Container>
  )
}

export default Home
